org.gradle.jvmargs=-Xmx6g -XX:MaxMetaspaceSize=2g -XX:+UseParallelGC -XX:+UseCompressedOops -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=android/heapdump.hprof

android.useAndroidX=true
android.enableJetifier=true

# Matikan incremental Kotlin compiler (menghindari error cache)
kotlin.incremental=false
kotlin.incremental.java=false
kotlin.incremental.useClasspathSnapshot=false

# Kadang membantu di Windows untuk path panjang
org.gradle.workers.max=4